spring.application.name=projeto
server.servlet.context-path=/api/v1

# Perfil ativo por padrão
spring.profiles.active=dev

# CONFIGURAÇÕES SPRING ACTUATOR
management.server.port=9090
management.endpoints.web.base-path=/actuator
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState

# CONFIGURAÇÕES TOKEN JWT
api.security.token.secret=${TOKEN_JWT_SECRET:chave-secreta}
api.security.token.issuer=${TOKEN_ISSUER:api-projeto-mais-pra-ti}
api.security.token.expiration-seconds=${TOKEN_EXPIRATION_SECONDS:3600}

# CONFIGURAÇÕES SEGURANÇA CORS
api.security.cors.allowed-origins=${API_SECURITY_CORS_ALLOWED_ORGINS:http://localhost:3000,http://localhost:5173,http://localhost:5500,http://127.0.0.1:*}
