# CONFIGURAÇÕES DO SERVIDOR
server.port=8080

# CONFIGURAÇÕES DO BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:projeto_final_dev}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# CONFIGURAÇÕES DOCUMENTAÇÃO SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# CONFIGURAÇÕES SPRING BOOT DEVTOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# CONFIGURAÇÕES DE LOG E DEBUG
logging.level.root=INFO

# CONFIGURAÇÕES JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# Mostra as queries SQL formatadas no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
