spring.application.name=projeto
server.servlet.context-path=/api/v1

# Perfil ativo por padrão
spring.profiles.active=dev

# CONFIGURAÇÕES SPRING ACTUATOR
management.server.port=9090
management.endpoints.web.base-path=/actuator
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState

