CREATE TABLE cloth_types (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             name        VARCHAR(30)                             NOT NULL,
                             description VARCHAR(255),
                             is_active   BOOLEAN                                 NOT NULL DEFAULT TRUE,
                             created_at  TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at  TIMESTAMP WITH TIME ZONE,
                             CONSTRAINT pk_cloth_types PRIMARY KEY (id),
                             CONSTRAINT uc_cloth_types_type UNIQUE (name)
);

CREATE TABLE collection_points (
                                   id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   name              VARCHAR(255)                            NOT NULL,
                                   point_picture_url VARCHAR(2048),
                                   is_active         BOOLEAN                                 NOT NULL DEFAULT FALSE,
                                   is_pending        BOOLEAN                                 NOT NULL DEFAULT TRUE,
                                   created_at        TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at        TIMESTAMP WITH TIME ZONE,
                                   street            VARCHAR(120)                            NOT NULL,
                                   number            VARCHAR(10)                             NOT NULL,
                                   complement        VARCHAR(30),
                                   neighborhood      VARCHAR(50)                             NOT NULL,
                                   city              VARCHAR(50)                             NOT NULL,
                                   state             VARCHAR(2)                              NOT NULL,
                                   country           VARCHAR(50)                             NOT NULL,
                                   zip_code          VARCHAR(8)                              NOT NULL,
                                   latitude          DECIMAL(10, 8),
                                   longitude         DECIMAL(11, 8),
                                   CONSTRAINT pk_collection_points PRIMARY KEY (id)
);

CREATE TABLE collection_point_operating_hours (
                                                  collection_point_id BIGINT                 NOT NULL,
                                                  day_of_week         VARCHAR(20)            NOT NULL,
                                                  opening_time        TIME WITHOUT TIME ZONE NOT NULL,
                                                  closing_time        TIME WITHOUT TIME ZONE NOT NULL,
                                                  CONSTRAINT fk_operating_hours_collection_point
                                                      FOREIGN KEY (collection_point_id) REFERENCES collection_points(id) ON DELETE CASCADE
);

CREATE TABLE collection_point_cloth_types (
                                              collection_point_id BIGINT NOT NULL,
                                              cloth_type_id       BIGINT NOT NULL,
                                              CONSTRAINT pk_collection_point_cloth_types
                                                  PRIMARY KEY (collection_point_id, cloth_type_id),
                                              CONSTRAINT fk_cp_cloth_types_cp
                                                  FOREIGN KEY (collection_point_id) REFERENCES collection_points(id) ON DELETE CASCADE,
                                              CONSTRAINT fk_cp_cloth_types_cloth
                                                  FOREIGN KEY (cloth_type_id) REFERENCES cloth_types(id) ON DELETE RESTRICT
);

CREATE TABLE collection_point_managers (
                                           collection_point_id BIGINT NOT NULL,
                                           user_id             BIGINT NOT NULL,
                                           CONSTRAINT pk_collection_point_managers
                                               PRIMARY KEY (collection_point_id, user_id),
                                           CONSTRAINT fk_cp_managers_cp
                                               FOREIGN KEY (collection_point_id) REFERENCES collection_points(id) ON DELETE CASCADE,
                                           CONSTRAINT fk_cp_managers_user
                                               FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE collection_point_operators (
                                            collection_point_id BIGINT NOT NULL,
                                            user_id             BIGINT NOT NULL,
                                            CONSTRAINT pk_collection_point_operators
                                                PRIMARY KEY (collection_point_id, user_id),
                                            CONSTRAINT fk_cp_operators_cp
                                                FOREIGN KEY (collection_point_id) REFERENCES collection_points(id) ON DELETE CASCADE,
                                            CONSTRAINT fk_cp_operators_user
                                                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_operating_hours_search
    ON collection_point_operating_hours (day_of_week, opening_time, closing_time);

CREATE INDEX idx_cp_cloth_types_cloth_id
    ON collection_point_cloth_types (cloth_type_id);

CREATE INDEX idx_cp_managers_user_id
    ON collection_point_managers (user_id);

CREATE INDEX idx_cp_operators_user_id
    ON collection_point_operators (user_id);

CREATE INDEX idx_collection_points_active_pending
    ON collection_points (is_active, is_pending);