CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uc_categories_name UNIQUE (name)
);

CREATE TABLE posts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(150)                            NOT NULL,
    slug            VARCHAR(150)                            NOT NULL,
    summary         TEXT                                    NOT NULL,
    body            TEXT                                    NOT NULL,
    category_id     BIGINT,
    created_by_id   BIGINT                                  NOT NULL,
    cover_image_url VARCHAR(2048),
    cover_image_alt VARCHAR(255),
    view_count      BIGINT                                  NOT NULL DEFAULT 0,
    is_published    BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT uc_posts_slug UNIQUE (slug),
    CONSTRAINT fk_posts_on_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_posts_on_author FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT
);


CREATE TABLE post_tags
(
    post_id BIGINT      NOT NULL,
    tag     VARCHAR(30) NOT NULL,
    CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag),
    CONSTRAINT fk_post_tags_on_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
);

CREATE TABLE post_cloth_types
(
    post_id       BIGINT NOT NULL,
    cloth_type_id BIGINT NOT NULL,
    CONSTRAINT pk_post_cloth_types PRIMARY KEY (post_id, cloth_type_id),
    CONSTRAINT fk_post_cloth_types_on_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_cloth_types_on_cloth_type FOREIGN KEY (cloth_type_id) REFERENCES cloth_types (id) ON DELETE CASCADE
);

CREATE INDEX idx_posts_category_id ON posts (category_id);
CREATE INDEX idx_posts_is_published ON posts (is_published);
CREATE INDEX idx_post_tags_post_id ON post_tags (post_id);
CREATE INDEX idx_post_cloth_types_cloth_id ON post_cloth_types (cloth_type_id);